version: '3.8'

services:
  # The main backend Django app
  main_app:
    image: library-backend-dev
    container_name: library_backend_dev
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - static:/static
      - venv:/app/venv
      - .:/app
    ports:
      - 8002:8002
    expose:
      - 8002
    env_file:
      - .env
    depends_on:
      - postgres


  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:85"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
 
volumes:
  static:
  venv:
  postgres-data:

